version: '3.8'

## NETWORKS ####

networks:
  transcendence-frontend:
    name: transcendence-frontend
    driver: bridge
  transcendence-backend:
    name: transcendence-backend
    driver: bridge
  transcendence-database:
    name: transcendence-database
    driver: bridge


## VOLUMES ####


volumes:
  vault-data:
  user-db:
  chat-db:
  friends-db:
  game-db:
  analytics-db:
  profile-db:



## DATABASES ####

services:
  user-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile

    image: user-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - user-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  chat-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile
    image: chat-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=chat_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - chat-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d chat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  friends-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile
    image: friends-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=friends_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - friends-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d friends_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  game-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile
    image: game-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=game_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - game-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d game_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  analytics-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile
    image: analytics-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=analytics_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - analytics-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d analytics_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  profile-db:
    build:
      context: ./postgres-databases
      dockerfile: Dockerfile
    image: profile-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=profile_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - profile-db:/var/lib/postgresql/data
    networks:
      - transcendence-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d profile_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


## SECRETS ####

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    image: vault
    env_file:
      - .env
    expose:
      - "8200"
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - vault-data:/vault
    cap_add:
      - IPC_LOCK
    networks:
      - transcendence-backend
    restart: unless-stopped
    depends_on:
      user-db:
        condition: service_healthy
      chat-db:
        condition: service_healthy
      friends-db:
        condition: service_healthy
      game-db:
        condition: service_healthy
      analytics-db:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


## MICRO SERVICES ####

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-gateway.token
    expose:
      - "8000"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-frontend
    depends_on:
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    image: user-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-user.token
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_NAME=user_db
    expose:
      - "8001"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      user-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  
  chat-service:
    build:
      context: ./backend/chat-service
      dockerfile: Dockerfile
    image: chat-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-chat.token
      - DB_HOST=chat-db
      - DB_PORT=5432
      - DB_NAME=chat_db
    expose:
      - "8002"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      chat-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  analytics-service:
    build:
      context: ./backend/analytics-service
      dockerfile: Dockerfile
    image: analytics-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-analytics.token
      - DB_HOST=analytics-db
      - DB_PORT=5432
      - DB_NAME=analytics_db
    expose:
      - "8003"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      analytics-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  friends-service:
    build:
      context: ./backend/friends-service
      dockerfile: Dockerfile
    image: friends-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-friends.token
      - DB_HOST=friends-db
      - DB_PORT=5432
      - DB_NAME=friends_db
    expose:
      - "8004"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      friends-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  game-service:
    build:
      context: ./backend/game-service
      dockerfile: Dockerfile
    image: game-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-game.token
      - DB_HOST=game-db
      - DB_PORT=5432
      - DB_NAME=game_db
    expose:
      - "8005"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      game-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  profile-service:
    build:
      context: ./backend/profile-service
      dockerfile: Dockerfile
    image: profile-service
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN_FILE=/vault/api-profile.token
      - DB_HOST=profile-db
      - DB_PORT=5432
      - DB_NAME=profile_db
    expose:
      - "8006"
    volumes:
      - vault-data:/vault:ro 
    networks:
      - transcendence-backend
      - transcendence-database
    depends_on:
      profile-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"] ## Route a ajouter dans le main.py
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

## FRONTEND ####

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-react
    ports:
      - "3000:3000"
    networks:
      - transcendence-frontend
    restart: unless-stopped

## WAF ####

  WAF:
    build:
      context: ./waf
      dockerfile: Dockerfile
    image: WAF
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence-frontend
    depends_on:
      api-gateway:
        condition: service_healthy
      frontend:
        condition: service_started
    restart: unless-stopped
